### ISSUE TITLE
If you die you teleport into a wall

### ISSUE THREAD

**Issue by LoneWolfHT** [C-C-Minetest-Server/parkour#1]
![image](https://user-images.githubusercontent.com/28972859/147032369-5fd0baf0-4831-49ec-a799-d7253ec6a07b.png)

- Go to level 2
- Bounce off the jelly and onto the floor (taking damage)
- Repeat until you die

(Set the player's damage groups to immortal to disable damage for them)

**Comment by Emojigit** [comment]
1. Why enable damage?
2. https://github.com/C-C-Minetest-Server/parkour/blob/d9cf007e2bd6d19c5f95803f154e45dd72d892cc/mods/pkr_init/init.lua#L57 this should be done

**Comment by Emojigit** [comment]
Fixed:

- BUGFIX: [on die stuck](https://github.com/C-C-Minetest-Server/parkour/commit/b613543ed622848ef65a1f6703788c66e931b228) (On `main`, `jam` and ContentDB)
